# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa36e488a423d2972a5438bcc0a70c6fdeea0e70ba8d4c976d15972a098ff8772b5c252daab1283ac8839c5330fd3da01061c8cb60b0659d42d2990f3417062c

test:
  secret_key_base: 13dc55e390ccc4242b6715593a4703d7b6a9cce75f4bcf6272dc17c6c00ad9536d35431b6759c94c78538289e6efe017ee0d6f501a39ac75f343e2dcfc04dd1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
